Add bookings
Ovarbor/java-shareit pull request #4
Opened 2022-12-10 12:50 UTC by Ovarbor

2022-12-10 18:48 UTC, andrew-larkin requested changes
Привет! Работа отличная, хорошая реализация. Остается немного скорректировать в некоторых местах и мы будем готовы двигаться в сторону пагинации)

2022-12-10 18:48 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingDto bookingCreated = bookingService.create(request, requesterId);
тут можно не создавать переменную bookingCreated - просто перенести метод сервиса внутрь скобок в body от ResponseEntity

2022-12-10 18:48 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Booking findByItemIdAndEndIsBefore(Long itemId, LocalDateTime end);
лучше возвращать объект модели в обертке Optional. Это более безопасный вариант на случай если ничего не будет найдено, по крайней мере с NPE мы уже не упадем

2022-12-10 18:48 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        Optional<Item> item = itemRepository.findById(request.getItemId());
у Optional есть отличный метод .orElseThrow(), внутрь котоорого можно вставить выброс ошибки - очень удобно, советую реализовать. Причем если ошибка выбрасываться не будет, то в переменной item мы получим готовый объект класса Item без всяких оберток

2022-12-10 18:48 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                return bookingMapper.toBookingDtoList(bookingRepository.findByBookerId(userId, page));
не забывай, что при поиске одного экземпляра класса в репозитории, мы можем его не найти и получим null. Поэтому важно обернуть в optional сам метод в репозитории, а тут использовать .orElseThrow, чтобы не наткнуться на null. Если возвращается не один экземпляр, а список, то необходимо удостовериться что он не пустой

2022-12-11 10:23 UTC, Ovarbor commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                return bookingMapper.toBookingDtoList(bookingRepository.findByBookerId(userId, page));
Не совсем понял, что имеется ввиду, сделал нечто такое:
switch (requestStatus) {
            case ALL:
                if (bookingRepository.findByBookerId(userId, page).isEmpty()) {
                    return new ArrayList<>();
                } else {
                    return bookingMapper.toBookingDtoList(bookingRepository.findByBookerId(userId, page));
                }

2022-12-24 08:58 UTC, merged