Add item requests
Ovarbor/java-shareit pull request #5
Opened 2022-12-24 09:10 UTC by Ovarbor

2022-12-25 09:21 UTC, andrew-larkin requested changes
Привет! Отличная работа, есть много удачных решений, хорошее покрытие тестами, архитектура тоже на хорошем уровне. Небольшой рефакторинг и мы будем готовы приступать к последней перед дипломом работе.

2022-12-25 09:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isBlank()) return ResponseEntity.ok().body(Collections.emptyList());
вот эту проверку лучше перенести в сервис, чтобы наши контроллеры оставались легковесными и не включали в себя доп.логику (тут должен соблюдаться первый принцип из SOLID)

2022-12-25 09:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getAll(@RequestHeader("X-Sharer-User-Id") Long ownerId,
ResponseEntity можно использовать

2022-12-25 09:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestController(ItemRequestService service) {
здесь можно как и в других контроллерах использовать @RequiredArgsConstructor

2022-12-25 09:21 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
когда мы используем пагинацию, можно наследоваться от специального репозитория PagingAndSortingRepository

2022-12-26 00:56 UTC, Ovarbor commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isBlank()) return ResponseEntity.ok().body(Collections.emptyList());
done

2022-12-26 00:56 UTC, Ovarbor commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getAll(@RequestHeader("X-Sharer-User-Id") Long ownerId,
done

2022-12-26 00:56 UTC, Ovarbor commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public ItemRequestController(ItemRequestService service) {
done

2022-12-26 00:56 UTC, Ovarbor commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +public interface ItemRequestRepository extends JpaRepository<ItemRequest, Long> {
done

2023-01-12 03:40 UTC, merged